{
 "title": "Home Network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skyhub_system_downstream_linerate"
    }
   ]
  },
  {
   "title": "WAN I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(skyhub_network_stats_tx_speed{interface=\"wan\"}[2m]) * 8",
     "legendFormat": "Up"
    },
    {
     "expr": "irate(skyhub_network_stats_rx_speed{interface=\"wan\"}[2m]) * 8",
     "legendFormat": "Down"
    },
    {
     "expr": "skyhub_system_upstream_linerate",
     "legendFormat": "Upstream rate"
    },
    {
     "expr": "skyhub_system_downstream_linerate",
     "legendFormat": "Downstream rate"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skyhub_network_uptime{interface=\"wan\"}",
     "legendFormat": "WAN Uptime"
    },
    { "expr": "skyhub_system_uptime", "legendFormat": "System Uptime" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "skyhub_system_upstream_linerate"
    }
   ]
  },
  {
   "title": "Attenuation",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skyhub_attenuation_down_db", "legendFormat": "{{interface}}" },
    { "expr": "skyhub_attenuation_up_db", "legendFormat": "{{interface}}" }
   ]
  },
  {
   "title": "Noise Margin",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skyhub_noise_margin_down_db", "legendFormat": "{{interface}}" },
    { "expr": "skyhub_noise_margin_up_db", "legendFormat": "{{interface}}" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 9 },
   "targets": [
    { "expr": "skyhub_connection_info" }
   ]
  },
  {
   "type": "annolist",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 13 },
   "targets": [
    { "expr": "skyhub_connection_info" }
   ]
  }
 ]
}